### ISSUE TITLE
java.net.URISyntaxException: Illegal character in scheme name at index 9: Favorites

### ISSUE THREAD

**Issue by turesheim** [Itema-as/eclipse-marketplace-server#105]
Looks like a problem with the catalog retrieved from http://marketplace.eclipse.org/catalogs/api/p

``` java
java.net.URISyntaxException: Illegal character in scheme name at index 9: Favorites
        http://www.eclipse.org/community/eclipse_newsletter/2016/may
        http://marketplace.eclipse.org/sites/default/files/marketplace_catalog_icon_0.png
    at java.net.URI$Parser.fail(URI.java:2848)
    at java.net.URI$Parser.checkChars(URI.java:3021)
    at java.net.URI$Parser.parse(URI.java:3048)
    at java.net.URI.<init>(URI.java:588)
    at org.eclipse.epp.internal.mpc.core.util.URLUtil.toURI(URLUtil.java:24)
    at org.eclipse.epp.internal.mpc.ui.catalog.ResourceProvider.retrieveResource(ResourceProvider.java:274)
    at org.eclipse.epp.mpc.ui.CatalogDescriptor.imageDescriptorForUrl(CatalogDescriptor.java:109)
    at org.eclipse.epp.mpc.ui.CatalogDescriptor.<init>(CatalogDescriptor.java:93)
    at org.eclipse.epp.internal.mpc.ui.commands.MarketplaceWizardCommand.installRemoteCatalogs(MarketplaceWizardCommand.java:315)
    at org.eclipse.epp.internal.mpc.ui.commands.MarketplaceWizardCommand.execute(MarketplaceWizardCommand.java:93)
```

**Comment by turesheim** [comment]
It should probably be possible to disable loading of the external catalogs. For the benefit of those that does not need it and to temporarily work around this bug.
